import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { BankProvider } from "@/context/BankContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter}  antialiased`}>
        <AuthProvider>
          <BankProvider>
            {children}
            <Toaster position="top-right" />
          </BankProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
